name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: Narenderbeniwal
          password: Narender@123

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/flask-calculator:latest
